# netlify.toml
# Tells Netlify how to serve the site

[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/photos/*"
  [headers.values]
    Cache-Control = "public, max-age=604800, immutable"
